name: upscalers

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - master
      - master-dev
    paths:
      - upscalers/*

permissions:
  id-token: write
  pages: write

jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-python@v6
        with:
          cache: pip
          python-version: '3.14'
          check-latest: true
          architecture: x64
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Install SteamCMD
        run: |
          mkdir steamcmd/
          cd steamcmd
          curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
      - name: Download Proton Experimental
        run: |
          mkdir sources/
          mkdir assets/
          ./steamcmd/steamcmd.sh +login anonymous +quit
          ./steamcmd/steamcmd.sh +force_install_dir $PWD/sources/proton_experimental +login anonymous +app_update 1493710 +quit
      - name: Make assets
        env:
          UPSCALERS_USER: ${{ github.repository_owner }}
          UPSCALERS_REPO: ${{ github.repository }}
          UPSCALERS_EVENT: ${{ github.event_name }}
        run: |
          python3 -m upscalers
      - uses: actions/upload-pages-artifact@v5
        id: deployment
        with:
          path: assets/

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-slim
    needs: fetch
    steps:
      - uses: actions/deploy-pages@v5
        id: deployment
